### ISSUE TITLE
Alternative MCU Packages

### ISSUE THREAD

**Issue by peterlok27** [weteor/3W6#2]
Hi! Thank you for your effort. I love the design idea. Can I just ask whether the QFN-44 is compatible with the PCB? TQFN-44 is rather hard to find where I'm at :((

**Comment by weteor** [comment]
Hi 

unfortunately the QFN-44 is not compatible with Rev2. It hat to be the TQFP package.

I've just checked and LCSC has them in stock and they deliver almost everywhere. Maybe that is an option?

You may also check Octoparts, which lists stock on a multitude of sites, maybe you can find something there:
https://octopart.com/search?q=atmega32u4-au&currency=USD&specs=0
