### ISSUE TITLE
Alternative microcontrollers? ATMEGA32U4-AU is hard to find

### ISSUE THREAD

**Issue by tqmai** [weteor/3W6#7]
Hi there, thanks again for creating this awesome keyboard! Very excited to build this and try it out. 

I've been having trouble sourcing ATMEGA32U4-AU microcontrollers - I've had two orders fall through already. Do you know of any alternative microcontrollers that would work for this board?

**Comment by BenRoe** [comment]
Last commit added support for ATMEGA32U4-AU and ATMEGA32U4-MU.
So issue can be closed.

**Comment by weteor** [comment]
right. I've changed the footprint to support both the AU and MU variant. So it's possible to choose the one which is cheaper
